INSERT OR IGNORE INTO chain_codes (code, name) VALUES
  ('AK', 'Aman Resorts'),
  ('AR', 'Aria Resort & Casino'),
  ('AV', 'Avani Hotels'),
  ('BH', 'Budgetel Inns'),
  ('BW', 'Best Western'),
  ('BY', 'Baymont'),
  ('CC', 'Clarion'),
  ('CI', 'Comfort Inn'),
  ('CN', 'Conrad Hotels'),
  ('CP', 'Crowne Plaza'),
  ('CY', 'Courtyard by Marriott'),
  ('DI', 'Days Inn'),
  ('DT', 'DoubleTree'),
  ('EC', 'Extended Stay America'),
  ('EH', 'Embassy Suites'),
  ('ES', 'Element by Westin'),
  ('EX', 'Fairfield Inn by Marriott'),
  ('FA', 'Fairmont'),
  ('FI', 'Fairfield Inn'),
  ('FN', 'Four Points by Sheraton'),
  ('FS', 'Four Seasons'),
  ('GI', 'Holiday Inn'),
  ('GN', 'Gaylord Hotels'),
  ('HG', 'Homewood Suites'),
  ('HH', 'Hilton Hotels'),
  ('HI', 'Holiday Inn'),
  ('HJ', 'Howard Johnson'),
  ('HL', 'Hilton'),
  ('HT', 'Hyatt Hotels'),
  ('HX', 'Hampton Inn'),
  ('HY', 'Hyatt'),
  ('IC', 'InterContinental'),
  ('IG', 'IHG'),
  ('IN', 'Hotel Indigo'),
  ('JW', 'JW Marriott'),
  ('KC', 'Kimpton Hotels'),
  ('KI', 'Kempinski'),
  ('LQ', 'La Quinta'),
  ('LW', 'Loews Hotels'),
  ('LX', 'Luxury Collection'),
  ('MC', 'Marriott'),
  ('MD', 'Le Meridien'),
  ('MO', 'Mandarin Oriental'),
  ('MU', 'Melia Hotels'),
  ('MV', 'Movenpick'),
  ('MZ', 'Moxy Hotels'),
  ('NH', 'NH Hotels'),
  ('NN', 'Novotel'),
  ('OZ', 'Omni Hotels'),
  ('PH', 'Park Hyatt'),
  ('PI', 'Pullman'),
  ('PY', 'Park Inn by Radisson'),
  ('QI', 'Quality Inn'),
  ('RA', 'Ramada'),
  ('RC', 'Ritz-Carlton'),
  ('RD', 'Radisson'),
  ('RE', 'Regent Hotels'),
  ('RI', 'Residence Inn'),
  ('RT', 'Mercure'),
  ('RZ', 'Radisson Blu'),
  ('SB', 'Sofitel'),
  ('SI', 'Sheraton'),
  ('SN', 'Sonesta'),
  ('SO', 'Shangri-La'),
  ('SP', 'SpringHill Suites'),
  ('SX', 'Six Senses'),
  ('TL', 'Travelodge'),
  ('TO', 'TownePlace Suites'),
  ('TR', 'Thistle Hotels'),
  ('TU', 'Tryp by Wyndham'),
  ('UI', 'Studio 6'),
  ('UP', 'Upscale Hotels'),
  ('VA', 'Vail Resorts'),
  ('VC', 'Viceroy'),
  ('VI', 'Vivanta'),
  ('VN', 'Vineyard Hotels'),
  ('WA', 'Waldorf Astoria'),
  ('WG', 'Wyndham Garden'),
  ('WH', 'W Hotels'),
  ('WI', 'Westin'),
  ('WR', 'St. Regis'),
  ('WY', 'Wyndham'),
  ('XR', 'Aloft Hotels'),
  ('YO', 'Yotel'),
  ('YX', 'Hyatt Place'),
  ('YZ', 'Hyatt House'),
  ('ZI', 'AC Hotels by Marriott');
